### ISSUE TITLE
VuGen may occasionally crash due FailFast call in WebBrowser control used in the add-in

### ISSUE THREAD

**Issue by HarinezumiSama** [MyLoadTest/LoadRunnerDocumentationAddin#2]
Here is the log record (from the Windows Event Log).

> Application: VuGen.exe
> Framework Version: v4.0.30319
> Description: The application requested process termination through System.Environment.FailFast(string message).
> Message: Unrecoverable system error.
> Stack:
>    at System.Environment.FailFast(System.String)
>    at **MS.Internal.Invariant.FailFast**(System.String, System.String)
>    at **MS.Internal.Controls.WebBrowserEvent.DocumentComplete**(System.Object, System.Object ByRef)
>    at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
>    at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
>    at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
>    at System.Windows.Application.RunDispatcher(System.Object)
>    at System.Windows.Application.RunInternal(System.Windows.Window)
>    at System.Windows.Application.Run(System.Windows.Window)
>    at ICSharpCode.SharpDevelop.Commands.WorkbenchStartup.Run(System.Collections.Generic.IList`1<System.String>)
>    at HP.Utt.Application.CallHelper.RunWorkbenchInternal(System.Object)
>    at HP.Utt.Application.CallHelper.RunWorkbench(HP.Utt.Application.WorkbenchSettings)
>    at HP.Utt.Application.ProductHost.RunWorkbench(HP.Utt.Application.WorkbenchSettings)
>    at HP.LR.Vugen.StartUp.VuGenMain.RunApplication()
>    at HP.LR.Vugen.StartUp.VuGenMain.Run()
>    at HP.LR.Vugen.StartUp.VuGenMain.Main(System.String[])

**Comment by HarinezumiSama** [comment]
Related discussion at MSDN Forum: https://social.msdn.microsoft.com/Forums/vstudio/en-US/e564d79b-0e2e-462e-88fe-2288dfbfc748/failfast-error-on-using-webbrowser-control-in-wpf?forum=wpf
